Asynchrounous refactoring
crystal-linux/amethyst pull request #22
Opened 2022-08-27 20:07 UTC by Trivernis

2022-08-27 20:56 UTC, Trivernis commented
Maybe I should just merge this into my forked main and do some heavy refactoring before merging

2022-08-27 21:42 UTC, not-my-segfault commented
> Maybe I should just merge this into my forked main and do some heavy refactoring before merging into upstream

Whichever works best for your workflow, we've currently got changes to the search feature on the development branch, but that's the only difference to main, so it might be a good idea to open up the PR against development.

I'm not gonna be doing any more work on Amethyst for now as I'm on holiday, so there shouldn't be much more extra work from doing so

2022-08-28 08:42 UTC, Trivernis commented
Nice, more conflicts

2022-08-29 23:04 UTC, not-my-segfault commented
Don't mind me just making sure things are tagged correctly

2022-09-03 17:04 UTC, Trivernis commented
I'm tired. Someone look at this and tell me it works

2022-09-03 17:07 UTC, not-my-segfault commented
> I'm tired. Someone look at this and tell me it works

I'm on my way!

2022-09-03 17:13 UTC, not-my-segfault commented
One issue I've noticed so far is that the indentation/word wrapping seems to be off in some places (I'm installing `aws-cli-git` as one of the examples provided by the [Arch Wiki page](https://wiki.archlinux.org/title/AUR_helpers#Legend)

![image](https://user-images.githubusercontent.com/30374463/188281389-6204576c-f205-4739-8138-5db4a423d891.png)

2022-09-03 17:17 UTC, Trivernis commented
> One issue I've noticed so far is that the indentation/word wrapping seems to be off in some places (I'm installing `aws-cli-git` as one of the examples provided by the [Arch Wiki page](https://wiki.archlinux.org/title/AUR_helpers#Legend)
> 
> ![image](https://user-images.githubusercontent.com/30374463/188281389-6204576c-f205-4739-8138-5db4a423d891.png)

lmao yea I just broke it

2022-09-03 17:18 UTC, not-my-segfault commented
~~`aws-cli-git` actually fails to install, this could be a result of it's non-standard PKGBUILD, worth looking into potentially?~~

It turns out not even `makepkg` seems to be able to handle this package. Lmao

![image](https://user-images.githubusercontent.com/30374463/188281508-120f6dfd-5f74-449e-aa71-2df1f3b805ca.png)

2022-09-03 17:19 UTC, not-my-segfault commented
![image](https://user-images.githubusercontent.com/30374463/188281603-7034e80c-2b56-41ac-8090-ddadb59ced62.png)
I'm not entirely sure what happened here?

2022-09-03 17:20 UTC, not-my-segfault commented
> ![image](https://user-images.githubusercontent.com/30374463/188281603-7034e80c-2b56-41ac-8090-ddadb59ced62.png) I'm not entirely sure what happened here?

![image](https://user-images.githubusercontent.com/30374463/188281619-c773c697-773e-44be-944c-071a02bf9815.png)

This is the output with `-vv`, super nondescriptive

2022-09-03 17:21 UTC, Trivernis commented
> > ![image](https://user-images.githubusercontent.com/30374463/188281603-7034e80c-2b56-41ac-8090-ddadb59ced62.png) I'm not entirely sure what happened here?
> 
> ![image](https://user-images.githubusercontent.com/30374463/188281619-c773c697-773e-44be-944c-071a02bf9815.png)
> 
> This is the output with `-vv`, super nondescriptive, is it potentially a PKGBUILD issue?

Exit code 9 would be RpcError tho. So something with the aur rpc

2022-09-03 17:22 UTC, not-my-segfault commented
I've noticed from all of this that the wiki page for AUR helpers is riddled with terrible PKGBUILDs, please for the love of god take a look at whatever the hell this is https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aws-cli-git

2022-09-03 17:24 UTC, Trivernis commented
> I've noticed from all of this that the wiki page for AUR helpers is riddled with terrible PKGBUILDs, please for the love of god take a look at whatever the hell this is https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aws-cli-git

God is dead

2022-09-03 17:25 UTC, axtloss commented
> I've noticed from all of this that the wiki page for AUR helpers is riddled with terrible PKGBUILDs, please for the love of god take a look at whatever the hell this is https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aws-cli-git

I'm going to cry

2022-09-03 17:25 UTC, SomethingGeneric commented
and you all complain about *my* pkgbuilds lmao

2022-09-03 17:25 UTC, SomethingGeneric commented
this is horrid

2022-09-03 17:25 UTC, Trivernis commented
The ros-melodic-desktop error is caused by a weird rpc response that cannot be parsed by serde. I have to fix that in the rpc wrapper pkg.
Serde didn't expect the Maintainer field to be null.

2022-09-03 17:26 UTC, not-my-segfault commented
Maybe supporting the AUR was a mistake. I'm going to retreat into a cave forever now, goodbye all! /j

2022-09-03 17:27 UTC, not-my-segfault commented
On a positive note, the new PKGBUILD parsing code seems to handle split pacakges beautifully! CLion was a super simple install process.

2022-09-03 17:30 UTC, not-my-segfault commented
Potentially terrible idea, we can actually handle shell completions for all AUR packages, as a list of all packages in the AUR is available as a GZIP-compressed plaintext file at https://aur.archlinux.org/packages.gz

I might experiment with how awful this would be to implement at some point

2022-09-03 17:32 UTC, not-my-segfault commented
One issue, when installing split packages like Clion (Which pulls in all of it's optdepends), every optdepend is installed as explicit. This can lead to cluttering the system with unnecessary packages

2022-09-03 17:44 UTC, not-my-segfault commented
Also a formatting thing, the `No pacnew files found` text should be bold

![image](https://user-images.githubusercontent.com/30374463/188282308-8d173b2b-070c-46b6-b108-aa08eaddfe44.png)

2022-09-03 18:09 UTC, Trivernis commented
> Potentially terrible idea, we can actually handle shell completions for all AUR packages, as a list of all packages in the AUR is available as a GZIP-compressed plaintext file at https://aur.archlinux.org/packages.gz
> 
> I might experiment with how awful this would be to implement at some point

lmao. We can just download that and put it in ~/.cache ig

2022-09-03 18:11 UTC, Trivernis commented
> One issue, when installing split packages like Clion (Which pulls in all of it's optdepends), every optdepend is installed as explicit. This can lead to cluttering the system with unnecessary packages

optdepends shouldn't be installed automatically

2022-09-03 18:31 UTC, Trivernis commented
Hmm, looks like pacman is doing it

2022-09-04 10:37 UTC, Trivernis commented
@axtloss @not-my-segfault I *slightly* refactored the aur install and split it into several files.
It should be readable now. I'd like to merge this (before it gets too big) if there's no other issues that weren't mentioned yet.

2022-09-04 10:38 UTC, not-my-segfault commented
Makes sense, I'll be free in around an hour to test it a bit further. Thanks for all the good work!

2022-09-04 10:40 UTC, axtloss commented
Yeah seems fine, although it should probably squash and merge to not clutter the git history

2022-09-04 10:42 UTC, Trivernis commented
> Yeah seems fine, although it should probably squash and merge to not clutter the git history

Squashing is kinda risky because you can quickly run into merge conflicts by doing that as it rewrites the history.
I had nothing but pain with squashing in the past.

2022-09-04 10:48 UTC, axtloss commented
oh then just a regular merge ig

2022-09-04 14:15 UTC, not-my-segfault commented
> Yeah seems fine, although it should probably squash and merge to not clutter the git history

We'll rebase and merge, that's part of our new Git workflow

2022-09-04 14:17 UTC, not-my-segfault requested changes

2022-09-04 14:17 UTC, not-my-segfault commented on Cargo.toml
> +
Some of the Cargo.toml file seems to have bit the dust, we no longer have the pkg-warner feature and i'd like to keep the `repository`, `keywords`, and `categories` keywords, so we can push to crates.io at some point

2022-09-04 14:23 UTC, not-my-segfault approved these changes

2022-09-04 14:24 UTC, not-my-segfault commented
There seem to be some merge issues that GitHub isn't telling us about for rebasing and committing. Sigh, I'll see what's up in Git lol

2022-09-04 14:26 UTC, Trivernis commented
> There seem to be some merge issues that GitHub isn't telling us about for rebasing and committing. Sigh, I'll see what's up in Git lol

Yea rebasing is witchcraft

2022-09-04 14:27 UTC, not-my-segfault commented
I'll manually rebase and push to `development`, thanks for all the great work again :)

2022-09-04 14:27 UTC, merged

2022-09-04 14:27 UTC, Trivernis commented
lol